### ISSUE TITLE
Usage instructions requires unmodified keymap

### ISSUE THREAD

**Issue by vramdal** [mjedynak/Builder-Generator#21]
From the plugin page at plugins.jetbrains.com I read that the plugin is invoked by pressing <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>B</kbd> inside a class.

However, that key combination is mapped to something else on my system, a Mac ("open task").

Is there another way to invoke the plugin?

**Comment by mjedynak** [comment]
You can find it in menu: Navigate->Builder.
You can also change the key mappings in: Settings -> Keymap.
