### ISSUE TITLE
Collections: The built object gets a reference to the live collection in the builder

### ISSUE THREAD

**Issue by nieldw** [mjedynak/Builder-Generator#22]
The generated builder is initialised with default, empty collections. When the object gets built, a live reference to that collection is passed to the built object. When that target object gets used and the collections on it is changed, that changes the state of the builder. When the builder is called again, it will build an object with collections containing the items added to the first target object! This is clearly not right.

The solution is simple: pass new collections to the target object.

```java
public class ItemBuilder {
    private Set<Long> longs = new HashSet<>(0);

    private ItemBuilder() {
    }

    public static ItemBuilder aPriceLstItem() {
        return new ItemBuilder();
    }

    public ItemBuilder withLongs(Set<Long> longs) {
        this.longs = longs;
        return this;
    }

    public Item build() {
        Item item = new Item();
        item.setLongs(new HashSet<>(longs));  // Initialise a new Set
        return item;
    }
}
```

**Comment by mjedynak** [comment]
Not sure if I understand the issue correctly.
The generated builder is NOT initialized with empty collection. All fields are always set within 'with' method by passing the reference.
In any case you should always create new builder if you want to build new object as the builder is stateful.
