### ISSUE TITLE
No fields are available in the dialog when I am generating a new builder class

### ISSUE THREAD

**Issue by rhhammond** [mjedynak/Builder-Generator#28]
I just installed the plugin, but I don't have the ability to select any fields when I am trying to create a new builder:

![image](https://cloud.githubusercontent.com/assets/1575005/17651474/4a0c06ae-622d-11e6-93e7-08cf3c192b03.png)

http://screencast.com/t/bdf42v8L5ZpG

**Comment by gauravsak** [comment]
Can you post the source code for the class you are trying to create this builder for?

**Comment by rhhammond** [comment]
I'm going to close this out, I thought it would automatically generate the ctor from final fields.  I got it working after some more experimentation.  Thanks.
